version: '3.7'
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    ports:
      - '8090:8090'
    volumes:
      - ./data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  vetixa:
    image: kferjani/vetixa:latest
    container_name: vetixa
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - pocketbase
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
